set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'https://github.com/morhetz/gruvbox'
Plugin 'https://github.com/kien/ctrlp.vim'
Plugin 'https://github.com/scrooloose/nerdtree'
Plugin 'https://github.com/terryma/vim-multiple-cursors'
Plugin 'https://github.com/bling/vim-airline'
Plugin 'https://github.com/scrooloose/syntastic/'
Plugin 'https://github.com/majutsushi/tagbar'
Plugin 'https://github.com/SirVer/ultisnips'
Plugin 'https://github.com/honza/vim-snippets'
Plugin 'https://github.com/Valloric/YouCompleteMe'

" Syntaxes
Plugin 'https://github.com/StanAngeloff/php.vim'
Plugin 'https://github.com/groenewege/vim-less'
Plugin 'https://github.com/othree/html5.vim'

call vundle#end()
filetype plugin indent on

let mapleader = ','

colorscheme gruvbox
syntax enable
set background=dark

" Ctrlp config
if executable('ag')
	let g:ctrlp_user_command = 'ag %s -l -u --nocolor -g ""'
	let g:ctrlp_use_caching = 0
endif

" Airline config
set laststatus=2
let g:airline#extensions#tabline#enabled = 1
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline#extensions#tabline#left_sep = ''
let g:airline#extensions#tabline#left_alt_sep = ''

" YouCompleteMe config
" use <CR> to select an item from youcompleteme
let g:ycm_key_list_select_completion=[]
let g:ycm_key_list_previous_completion=[]

" Mappings
nmap <leader>p :CtrlPCurWD<CR>
nmap <leader>r :CtrlPBufTag<CR>
nmap <leader>b :CtrlPBuffer<CR>
nmap <leader>t :NERDTreeToggle<CR>
nmap <leader>R :TagbarToggle<CR>
nmap <leader>n :bprev<CR>
nmap <leader>m :bnext<CR>
nmap <leader>q :bd<CR>
nmap <leader>h :set hlsearch! hlsearch?<CR>

set number
set mouse=a
set foldmethod=indent
set foldlevelstart=20
set incsearch
set hlsearch
set cursorline
set expandtab
set tabstop=4
set shiftwidth=4
set backspace=2
